export const headCells = [
  {
    id: 'eventName',
    label: 'Event Name',
    className: 'event-name',
  },
  {
    id: 'ptaName',
    label: 'PTA Name',
    className: 'pta-name',
  },
  {
    id: 'pupils',
    label: 'Pupils',
    className: 'pupils',
  },
  {
    id: 'date',
    label: 'Date',
    className: 'date',
  },
  {
    id: 'orders',
    label: 'Orders / Value',
    className: 'orders',
  },
  {
    id: 'actions',
    label: 'Actions',
    className: 'actions',
  },
];

export const rows = [
  {
    id: 1,
    eventName: 'Disco',
    ptaName: 'Folkestone Primary',
    pupils: 20,
    date: '23 May 2023',
    count: 54,
    amount: 1278,
    currency: '£',
  },
  {
    id: 2,
    eventName: 'Museum',
    ptaName: 'Folkestone Primary',
    pupils: 50,
    date: '23 May 2023',
    count: 74,
    amount: 2000,
    currency: '£',
  },
  {
    id: 3,
    eventName: 'Atlantic Museum in Somewhere in Australia',
    ptaName: 'Folkestone Primary',
    pupils: 100,
    date: '23 May 2023',
    count: 104,
    amount: 3000,
    currency: '£',
  },
  {
    id: 4,
    eventName: 'Atlantic Museum in Somewhere in Australia',
    ptaName: 'Folkestone Primary',
    pupils: 100,
    date: '23 May 2023',
    count: 104,
    amount: 3000,
    currency: '£',
  },
  {
    id: 5,
    eventName: 'Atlantic Museum in Somewhere in Australia',
    ptaName: 'Folkestone Primary',
    pupils: 100,
    date: '23 May 2023',
    count: 104,
    amount: 3000,
    currency: '£',
  },
  {
    id: 6,
    eventName: 'Atlantic Museum in Somewhere in Australia',
    ptaName: 'Folkestone Primary',
    pupils: 100,
    date: '23 May 2023',
    count: 104,
    amount: 3000,
    currency: '£',
  },
];